swagger: '2.0'
info:
  title: 视觉质检系统
  version: '1.0'
host: URL
schemes:
  - http
  - https
basePath: /apis/v1.0
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  basic:
    type: basic
security:
  - basic: []
  - {}
paths:
  /runs:
    get:
      summary: 检测结果列表
      description: 此接口获取全部检测的结果（待检测，正在检测，已检测完成）
      responses:
        '200':
          description: 正常情况下，返回全部检测结果
          schema:
            $ref: '#/definitions/RunList'
        '500':
          description: 服务端错误。错误代码
          schema:
            $ref: '#/definitions/Errors'
  /run:
    get:
      summary: 检测结果查询
      description: 此接口根据检测ID获取单次检测结果
      parameters:
        - $ref: '#/parameters/queryId'
      responses:
        '200':
          description: 查询完成。返回对应检测的结果
          schema:
            $ref: '#/definitions/Run'
        '404':
          description: 请求错误
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: 服务端错误
          schema:
            $ref: '#/definitions/Errors'

    post:
      summary: 检测请求提交
      description: 此接口将本地信息上传到质检系统中，返回得到一次检测的唯一编号以供后续查询
      parameters:
        - $ref: '#/parameters/runSubmit'
            
      responses:
        '201':
          description: 已提交。返回检测请求的ID
          schema:
            $ref: '#/definitions/UniqueId'
        '400':
          description: 请求错误
          schema:
            $ref: '#/definitions/Errors'
        '500':
          description: 服务端错误
          schema:
            $ref: '#/definitions/Errors'
parameters:
  queryId:
    name: query_id
    description: 检测唯一编号
    in: query
    required: true
    type: string
  runSubmit:
    name: run_submit
    description: 提交检测请求时的信息
    in: body
    required: true
    schema:
      $ref: '#/definitions/RunSubmit'
  
definitions:
  Errors:
    description: 错误列表。当请求失败时返回的错误列表
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Error'
  Error:
    description: 请求失败时发生的错误
    type: object
    properties:
      code:
        type: string
        description: 错误编号
      message:
        type: string
        description: 错误消息
  UniqueId:
    type: string
    description: 每次提交检测的唯一ID
  StationId:
    type: integer
    description: 工站ID
  SearchKey:
    type: string
    description: 搜索关键词
  OrderList:
    type: array
    items:
      $ref: '#/definitions/Brick'
  RunSubmit:
    type: object
    description: 检测请求提交时的数据结构
    properties:
      station_id:
        $ref: '#/definitions/StationId'
      search_key:
        $ref: '#/definitions/SearchKey'
      order_list:
        $ref: '#/definitions/OrderList'
  RunList:
    type: array
    description: 检测请求列表
    items:
      $ref: '#/definitions/Run'
  Run:
    type: object
    description: 检测请求模型
    properties:
      id:
        type: integer
        format: int64
        description: 检测请求ID
      status:
        type: string
        description: 检测请求状态：待检测/正在检测/检测完成
      bricks:
        type: array
        description: 检测结果（工站采集图像中包含的积木信息）
        items:
          $ref: '#/definitions/Brick'
  Brick:
    type: object
    properties:
      shape_id:
        type: string
        description: 积木形状ID
      shape_desc:
        type: string
        description: 积木形状描述
      color_id:
        type: string
        description: 积木颜色ID
      color_desc:
        type: string
        description: 积木颜色描述
