services:
  web:
    hostname: web
    build: .
    command: bash ./start.sh
    ports:
      - 8000:8000
    networks:
      - inner
    depends_on:
      - camera-server
      - worker
      - redis
      - db
    volumes:
      - ./share:/share:rw
  worker:
    hostname: worker
    build: .
    command: python manage.py rqworker
    networks:
      - inner
    depends_on:
      - redis
    volumes:
      - ./share:/share:rw
  camera-server:
    hostname: camera-server
    build: .
    command: python -m camera.server
    privileged: true
    networks:
      - inner
    ports:
      - 33033:33033
    volumes:
      - ./share:/share:rw
  redis:
    hostname: redis
    image: redis:7.0.7
    command: redis-server /etc/redis/redis.conf
    networks:
      - inner
    volumes:
      - ./redis:/etc/redis:ro
  db:
    image: mysql:8.0.31-debian
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/mysql.cnf:/etc/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ddi3239h8#LUlJ#O@#J
      TZ: Asia/Shanghai
    networks:
      - inner

networks:
  inner:
    # external: true
    # name: host
