# Generated by Django 4.1.4 on 2022-12-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionrequest',
            name='order_id',
        ),
        migrations.AddField(
            model_name='detectionrequest',
            name='order_list',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
