# Generated by Django 4.1.5 on 2023-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_detectionrequest_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('brick_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
