# Generated by Django 4.1.5 on 2023-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_brick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brick',
            name='brick_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='brick',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
